apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-exec-role" (include "jenkins-inbound-agent.serviceAccountName" .) }}
  namespace: jenkins
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-agent-exec-binding
  namespace: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ printf "%s-exec-role" (include "jenkins-inbound-agent.serviceAccountName" .) }}
subjects:
  - kind: ServiceAccount
    name: {{ include "jenkins-inbound-agent.serviceAccountName" . }}
    namespace: jenkins
